name = "Lax115662"
defaultTargets = ["Lax115662"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[lean_lib]]
name = "Lax115662"

[[require]]
name = "Lax434930"
git = "https://github.com/EdouardBonnet/classical-complexity"
rev = "0c0840319318215fd7b36a9a822b81ce55cf6941"
subDir = "concepts"
